### PR TITLE
Add ability to ignore JWT expiration

### PR DESCRIPTION
**Pull request by sysradium**
Add `IgnoreExpiration` option so user can allow expired token to be treated as valid. Sometimes is useful.

### CODE REVIEW

**Comment by NicoGonMu** [comment]
That would be useful!

**Comment by ciehanski** [comment]
I am curious where this would be useful?

**Comment by grounded042** [comment]
Thanks for the PR @sysradium! According to [RFC7519](https://tools.ietf.org/html/rfc7519) ignoring the expiration time is not something we should do. You do have the option of passing tokens that don't have an expiration claim. 

If this request is related to clock skew (see #58) I would be open to a proposal that would allow for support of that.

**Comment by sysradium** [comment]
Thanks 👍

**Pull request closed without merging**
