### PR TITLE
Fix the negroni example

### PR DESCRIPTION
**Pull request by sebest**

### CODE REVIEW

**Comment by mgonto** [comment]
Hey,

Thanks for the fixes :).

I see in the diff that you're using Tabs instead of spaces. Could you change it to spaces and submit the PR again? It's showing changes on all lines just because of that. Once that's done I'll merge.

Thanks!

**Comment by sebest** [comment]
this is the output of 'go vet' , you prefer spaces?

**Comment by mgonto** [comment]
It's already spaces so if you can, yeah :). Sorry about that!

**Comment by sebest** [comment]
ok, i will fix it :)

**Comment by sebest** [comment]
In the initial README there was a mix of 2 spaces, 4 spaces and tabs.
I converted everything to 2 spaces and i also fixed the first example.
I also added the content of the Claim in the response handler to give an example of accessing it.

**Comment by mgonto** [comment]
Thanks for everything :).

Merging!

**Pull request merged**
