### PR TITLE
Bearer or JWT

### PR DESCRIPTION
**Pull request by theromis**
My clients uses JWT, hard to change all clients immediately.

### CODE REVIEW

**Comment by grounded042** [comment]
Hey @theromis, thanks for the PR. The accepted practice as defined in [RFC6750](https://tools.ietf.org/html/rfc6750) is to use `Bearer` before the token in an `Authorization` header. If you would like to use a custom header value other than `Bearer` you are welcome to pass in your own `TokenExtractor` function in the `Options`.

**Comment by theromis** [comment]
@grounded042 thank you for clarification, will try this approach.

**Comment by grounded042** [comment]
I did understand what it was for - could you explain what the benefit / functionality of it is?

**Comment by theromis** [comment]
@grounded042 sorry for late reply, getting a lot of stuff in parallel.
Using `ParseWithClaims` gives ready to use `struct` versus `map[string]string` where every request have to be wrapped by bunch of `if * else` statements. What do you think by having extra function which will give this functionality?

**Comment by grounded042** [comment]
Ah, ok - I see. I'm not opposed to that, however I see several problems that would have to be overcome: 
- the options struct is a request independent object - by adding the `GetClaims` function we now have request specific functionality in there which I am not seeing how one could easily use for its intended purpose (individual requests).
- I would like to avoid breaking changes so this would need to be coded in a backwards compatible way.

**Pull request closed without merging**
