### PR TITLE
Isolate example-only dependencies

### PR DESCRIPTION
**Pull request by liggitt**
### Description

Add a separate go.mod file specifically for the examples package and tidy the top-level go.mod file to avoid propagating unnecessary dependencies on unmaintained transitive modules.

Spotted when switching to this module in https://github.com/kubernetes/kubernetes/pull/102755#discussion_r655677449

### CODE REVIEW

**Review by grounded042 — APPROVED** [review]

**Comment by liggitt** [comment]
thanks! any chance of getting a v1.0.1 tagged? it looks like no changes to the library code have been made since v1.0.0, which is ideal

**Comment by liggitt** [comment]
ha, beat me by 30 seconds :)

**Comment by grounded042** [comment]
Thanks for the cleanup @liggitt! ;)

**Comment by grounded042** [comment]
Oh, @liggitt - we will hopefully be releasing a new major version of this package soon to clean some more things up. I don't think it should impact you at all since it looks like this is a transitive dependency, but I wanted to let you know.

**Comment by PushkarJ** [comment]
@grounded042 thank you so much, with the super fast tagged release :)

**Pull request merged**
