### PR TITLE
Observability with OpenTelemetry

### PR DESCRIPTION
**Pull request by dmathieu**
## Description

This PR proposes to make middleware requests observable by instrumenting them with OpenTelemetry.

Here is an example of a trace with this PR applied.
Note: there is way more data than seen in this screenshot, within the spans attributes and events.

The `hello-world` span is a dummy one created within the HTTP handler once authenticated.

Screenshot 2022-06-10 at 09 12 55

And for reference, this is what the same request looks like without any instrumentation.
Screenshot 2022-06-10 at 09 14 21

### But what people who don't use OpenTelemetry?

Anybody not instrumenting their applications with OpenTelemetry will not see any change. The retrieved tracer will be a noop, and the created spans will not be persisted into memory.
As soon as they setup the otel instrumentation, they will start seeing spans though.

## Testing

This doesn't technically modify any behavior.
It can be tested by running the middleware on an application with OpenTelemetry configured, and looking at spans.

## Checklist

- [x] I have read and agreed to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).
- [x] I have read the [Auth0 General Contribution Guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).
- [x] I have reviewed my own code beforehand.
- [x] I have added documentation for new/changed functionality in this PR.
- [x] All active GitHub checks for tests, formatting, and security are passing.
- [x] The correct base branch is being used, if not `master`.

### CODE REVIEW

**Comment by grounded042** [comment]
@dmathieu you need to have your branch be on this repo for semgrep to pass.

**Comment by cocojoe** [comment]
@dmathieu this is a feature add and should have documentation in the README for customer awareness and how to use it etc

@dmathieu do you have a supporting customer ask for this? (internal or external)

@Widcket @adamjmcgrath please can you review this in and also think about the wider implication as this sort of feature add from a consistency perspective would be something we would then have to consider applying across relevant SDKs. e.g. it is something we want to support.

I'll also raise an internal discussion.

**Comment by dmathieu** [comment]
This was a hackathon project. I don't have a specific customer ask (outside of me on a side project).
We have a meeting with @kevlil83 and @stevehobbsdev on friday to talk next steps about this (ideally, it'd be great if observability came into all SDKs, not just go).

**Comment by RiverPhillips** [comment]
This would be really helpful, is there anything blocking this from being merged?

**Comment by dmathieu** [comment]
Hi,
Thank you for your interest. Customers interested in this is exactly what we need at the moment :)

This came from an internal hackathon, and therefore without any product reflexion. Before we ship it, we want to ensure we can support it as a full-blown feature, and not just as a hack which is unofficially there.

**Comment by sergiught** [comment]
Thanks for raising this @dmathieu 👋🏻 

After some discussion with @adamjmcgrath and the team, we feel that the best solution for the broadest set of customers is to make sure this SDK is extensible enough to use with any telemetry solution rather than a specific vendor.

If you feel there’s any extensibility points missing from this SDK that is preventing you from doing this, please feel free to raise an issue or a PR.

**Pull request closed without merging**
